### ISSUE TITLE
[NFR] Add max_buffer in settings to control nodejs maxBuffer size

### ISSUE THREAD

**Issue by taietel** [kylefarris/clamscan#13]
If you try to scan folders with more than 4k files there's a chance to get an error like this `There was an error! Error: stdout maxBuffer exceeded.`, this is because nodejs's buffer is set to 200*1024 bytes. 
It would be nice to have a way to control this, without hacking the code inside the module.

**Comment by kylefarris** [comment]
@taietel Thanks again for the bug reporting. This is a scenario that I hadn't come across yet in my own usage of the module. The "simple" solution would be to provide this maxBuffer size option to the module, but, I think that might be rather confusing for some people--not very user-friendly in other words. 

The problem is arising from running the following command through the `execFile` method of Node's `child_process` library:

```sh
find /path/to/your/directory
```

This would return a newline-delimited string to stdout (which has that aforementioned default buffer max size of 200 * 1024). I could obviously set that number to an artificially high 1024 * 1024 or something, but, what if the buffer exceeds that? I could allow devs to set their own number but what if they miscalculate? No need for senseless bugs.

I think the solution would be to not use `child_process.execFile` and instead use `child_process.spawn` and then chunk out that stream into 200 * 1024 bytes that could then be scanned a bit at a time. This will take a bit more effort, obviously, but will be a much more robust solution.

I'll see what I can do.

**Comment by kylefarris** [comment]
Passing in file streams is no possible with the `scanStream` method. That should likely resolve this issue.
