### ISSUE TITLE
Check on file chunk

### ISSUE THREAD

**Issue by farskid** [kylefarris/clamscan#17]
I wanna check for viruses on upload process, and the uploader is sending file to server in chunks.
Can the clamscan package verify the health of a chunk and is it safe to assume, if a chunk of file is healthy, so the whole file would be healthy too?

**Comment by kylefarris** [comment]
The latest version that I'm currently working on (you can see the code in the `sockets` branch) will allow you to scan streams of data. In other words, if at any point, the the scanner detects a virus in the stream, the stream can be stopped and handled there. Stay tuned.

**Comment by kylefarris** [comment]
Version 1.0.0 is out and supports this feature somewhat. Unfortunately, as cool as it would be to scan chunks of a file, ClamAV doesn't support scanning until the entire stream has been received. I tried to figure out how to get this to work but ultimately concluded that it wouldn't really be possible. And, really, it makes sense because, depending on the size of the chunks, a match it might be looking for could be split between two chunks and if it checked after each concatenation scan time would be lengthened to extreme degree because it would have to scan _n_ number of times where each time the scan would take longer (bigger chunk of code).

I hope you find some value in v1.x.x as it provides some really nice features like the `passthrough` method.
